version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - .db/db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - "8005:3306"

volumes:
  db_data: